# Generated by Django 5.1.4 on 2025-01-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_tax"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tax",
            options={"verbose_name_plural": "tax"},
        ),
    ]
