# Generated by Django 5.1.4 on 2026-03-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_fooditem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="allergen_info",
            field=models.CharField(
                blank=True,
                help_text="e.g., Contains nuts, gluten, dairy",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="is_spicy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="is_veg",
            field=models.BooleanField(default=False),
        ),
    ]
