# Generated by Django 5.1.4 on 2026-03-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_total_data_order_vendors"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_discount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("PayPal", "PayPal"), ("RazorPay", "RazorPay")], max_length=100
            ),
        ),
    ]
